#!/usr/bin/env lua

fields={}
files={}

function esc(x)
   return (x:gsub('%%', '%%%%')
	    :gsub('^%^', '%%^')
	    :gsub('%$$', '%%$')
	    :gsub('%(', '%%(')
	    :gsub('%)', '%%)')
	    :gsub('%.', '%%.')
	    :gsub('%[', '%%[')
	    :gsub('%]', '%%]')
	    :gsub('%*', '%%*')
	    :gsub('%+', '%%+')
	    :gsub('%-', '%%-')
	    :gsub('%?', '%%?'))
end

if arg[1]~="-s" or #arg<2 then
	io.stderr:write("splitup -s SEP [FILES]\n")
	os.exit(1)
end

sep=arg[2]
i=1; c=3

while c<=#arg do
	files[i]=io.open(arg[c], "w")
	i=i+1
	c=c+1
end

line=io.read()

while line~=nil do
	for i=1, #files-1 do
		p1, p2=line:find(sep)

		if p1==nil or p2==nil then
			if line~="" then
				fields[i]=line
				line=""
			else
				fields[i]=""
			end
		else
			fields[i]=line:sub(1, p1-1)
			line=line:gsub("^"..esc(fields[i])..sep, "")
		end
	end
	fields[#files]=line

	for i=1, #files do
		files[i]:write(fields[i].."\n")
	end
	line=io.read()
end

for i=1, #files do
	files[i]:close()
end
