.TH TREAT 1
.SH NAME
treat \- run different fields of the input through different filters

.SH SYNOPSIS
program [-i INSEP] [-o OUTSEP] [FILTERS]

.SH DESCRIPTION
treat runs different input fields through different text filters
specified by the user.  The nth field is run through the nth filter
specified. If no filter is specified for a field, the field is run through
cat(1). The resulting fields are pasted together and printed. Without
any arguments, treat behaves like cat.

.SH OPTIONS
.TP
.BI \-i " INSEP"
use INSEP as input separator (format lua regex), defaults to tabs/spaces.
.TP
.BI \-o " OUTSEP"
use OUTSEP as output separator (argument for paste -d), defaults to tab.

.SH EXAMPLES
.TP
.B treat
.TP
behave like cat.
.TP
.B du -ab | treat human 'xargs basename -a'
print human readable sizes of the different files in the directory tree.
Uses the human(1) utility by z3bra.
.P
.B echo -e 'a b\enc d\engh flbb xq' | treat -o ' ' "sed 's/$/e/'" | tr '\en' '|'
.br
.B ae b|ce d|nghe flbb xq|
.TP
.B df | sed 1d | tr -s ' ' | awk '{ print($1, $2*1024, $3*1024, $4*1024, $5, $6) }' | treat cat human human human | column -t
Mimick du -h (without the first line).

.SH BUGS
Sometimes paste says it didn't find one of the output fifos. They exist,
and I have no idea why this happens. I'm sorry.

.SH "SEE ALSO"
.IR mkfifo(1),
.IR paste(1),
.IR pee(1)
included in moreutils.

.SH AUTHOR
pranomestro@gmail.com
