.Dd May 11, 2017
.Dt TREAT 1
.Os

.Sh NAME
.Nm treat
.Nd run different fields through different filters

.Sh SYNOPSIS
.Nm
.Op Fl s Ar insep
.Op Fl o Ar outsep
.Op Ar filters

.Sh DESCRIPTION
.Nm
runs the nth input field from stdin through the nth filter specified
as a cli argument. If no filter is specified for a field, the field is
run through cat. The resulting fields are pasted together and printed
to stdout.

.Sh OPTIONS
.Bl -tag -width Ds
.It Fl s Ar insep
Use
.Ar insep
as the input field separator, defaults to spaces (\(dq \(dq).
.It Fl o Ar outsep
Specify
.Ar outsep
as the output field separator, defaults to tab (\(dq\et\(dq).

.Sh FILES
.Bl -tag -width Ds
.It Pa /tmp/treat.XXXXXX
The temporary directory where treat stores the FIFOs for
piping the different fields.
.El

.Sh EXAMPLES
Emulate cat:
.Pp
.Dl $ treat
.Pp
Print human readable sizes of the different files in the directory tree:
.Pp
.Dl $ du -ab | treat human 'xargs basename -a'
.Pp
Execute sed on only one field:
.Pp
.Dl $ printf 'a b\enc d\eng flbb xq' | treat -o ' ' "sed 's/$/e/'" | tr '\en' '|'
.Dl ae b|ce d|nge flbb xq|
.Pp
Emulate du -h (without the header line):
.Pp
.Dl df | sed 1d | tr -s ' ' | awk '{ print($1, $2*1024, $3*1024, $4*1024, $5, $6) }' | treat cat human human human | column -t

.Sh EXIT STATUS
.Ex -std

.Sh SEE ALSO
.Xr awk 1 ,
.Xr basename 1 ,
.Xr cat 1 ,
.Xr column 1 ,
.Xr df 1 ,
.Xr echo 1,
.Xr human 1 ,
.Xr mkfifo 1 ,
.Xr numfmt 1 ,
.Xr paste 1 ,
.Xr pee 1 ,
.Xr sed 1 ,
.Xr tr 1,
.Xr xargs 1 .

.Sh AUTHORS
.An pranomostro Aq Mt pranomestro@gmail.com
